#!/usr/bin/env bash
usage="$(basename "$0") OPTIONS [path] -- display ordered directory sizes

OPTIONS:
    -h          Show this help message
    -n x	Only show first x rows

FUNCTION:
    path        Directory path to use as root dir, default current directory
"
usage() {
    echo "$usage"
    exit 1
}

ROOT=.
N=0

for option in "$@"
do
    case $option in
        -h|--help) usage;;
        -n=*|--n=*) N=${option#*=}; shift;;
        -n|--n) N=$2; shift; shift;;
        -*|--*|\?) printf "illegal option: %s\n\n" "$option" >&2; usage;;
    esac
done

if [ $# -gt 1 ]; then
    usage
elif [ ! -z "$1" ]; then
    ROOT=$1
fi

##

if [ "$N" -eq "0" ]; then
    du -h -d0 $ROOT/* | sort -hr
else
    du -h -d0 $ROOT/* | sort -hr | head -n $N
fi

exit $?
